pomme/models/entry.py
from playhouse.sqlite_ext import FTS5Model
from playhouse.sqlite_ext import SearchField

from pomme import pomme_db


class Entry(FTS5Model):
    msgid = SearchField()
    msgstr = SearchField()
    id_lang = SearchField()
    str_lang = SearchField()
    crawl_timestamp = SearchField(unindexed=True)
    source_url = SearchField(unindexed=True)
    license = SearchField(unindexed=True)

    class Meta:
        database = pomme_db


if not Entry.table_exists():
    Entry.create_table()

pomme/forms/search.py
from flask_wtf import FlaskForm
from wtforms import SelectField
from wtforms import StringField
from wtforms import SubmitField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    search_word = StringField("Word", validators=[DataRequired()])
    id_lang = SelectField("Source Language", choices=["en"], default="en")
    str_lang = SelectField("Dest Language", choices=["fr"], default="fr")
    submit = SubmitField("Search!")

pomme/__init__.py
import logging
import os

from celery import Celery
from dotenv import load_dotenv
from flask import Flask
from peewee import OperationalError
from peewee import SqliteDatabase


POMME_ROOT = os.path.join(os.path.dirname(__file__), "../")  # refers to repository root
dotenv_path = os.path.join(POMME_ROOT, ".env")
load_dotenv(dotenv_path)

REQUIRED_ENV_VARS = [
    "FLASK_PORT",
    "FLASK_DEBUG",
    "FLASK_HOST",
    "FLASK_SECRET_KEY",
    "CELERY_BROKER_URL",
    "CELERY_RESULT_BACKEND",
    "GH_TOKEN",
]

for item in REQUIRED_ENV_VARS:
    if item not in os.environ:
        raise EnvironmentError(
            f"{item} is not set in the server's environment or .env file. It is required."
        )

from pomme.static import FLASK_SECRET_KEY, CELERY_RESULT_BACKEND, CELERY_BROKER_URL


application = Flask(__name__)

if (
    os.getenv("FLASK_DEBUG", "false") == "true"
    or os.getenv("FLASK_DEBUG", "false") == "1"
):
    application.debug = True
else:
    application.debug = False

application.secret_key = FLASK_SECRET_KEY
application.config.update(FLASK_SECRET_KEY=FLASK_SECRET_KEY)

pomme_db = SqliteDatabase(database=POMME_ROOT + "/pomme.db")


# Opens the DB connection before each request
@application.before_request
def open_db():
    try:
        pomme_db.connect()
    except OperationalError:
        pass


# Closes the DB connection after each request
@application.after_request
def close_db(response):
    if not pomme_db.is_closed():
        pomme_db.close()
    return response


# Celery configuration
application.config["CELERY_broker_url"] = CELERY_BROKER_URL
application.config["result_backend"] = CELERY_RESULT_BACKEND

logging.debug("Initializing Celery")
# Initialize Celery
celery = Celery(application.name, broker=CELERY_BROKER_URL)
celery.conf.update(application.config)


from pomme.routes.views.home import home_bp

application.register_blueprint(home_bp)


# import tasks here to be registered by celery

import pomme.tasks.crawl_github  # noqa


# Import models to be registered and created

from pomme.models.entry import Entry  # noqa

pomme/routes/views/home.py
from flask import Blueprint
from flask import flash
from flask import render_template

from pomme.forms.search import SearchForm
from pomme.models.entry import Entry

home_bp = Blueprint("home", __name__)


@home_bp.route("/", methods=["GET"])
def home_view():
    return render_template("home.html")


@home_bp.route("/metrics", methods=["GET"])
def metrics_view():
    return render_template("metrics.html")


@home_bp.route("/search", methods=["GET", "POST"])
def search_view():
    form = SearchForm()
    # TODO: Optimize this with .distinct() if you can get it working
    form.id_lang.choices = list(set([entry.id_lang for entry in Entry.select()]))
    form.str_lang.choices = list(set([entry.str_lang for entry in Entry.select()]))
    if form.validate_on_submit():
        word = form.search_word.data
        id_lang = form.id_lang.data
        str_lang = form.str_lang.data
        search_results = Entry.search(word).where(
            Entry.id_lang == id_lang, Entry.str_lang == str_lang
        )
        count = search_results.count()
        result_list = []
        for result in search_results:
            result_list.append(
                {"rowid": result.rowid, "msgid": result.msgid, "msgstr": result.msgstr}
            )
        flash(f"Found {count} results for '{word}'", "success")
        return render_template(
            "search.html", form=form, results=result_list, search_word=word
        )
    return render_template("search.html", form=form, results=None)


@home_bp.route("/crawl", methods=["GET"])
def crawl_view():
    return render_template("crawl.html")

pomme/templates/base.jinja2.html
<!DOCTYPE html>
<html>

{% include "parts/header.jinja2.html" %}

{% block body %}
    <body id="page-top">
    <div id="wrapper">
        {% include "parts/sidebar.jinja2.html" %}
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                {% include "parts/searchbar.jinja2.html" %}
                {% include "parts/flashes.jinja2.html" %}
                {% block content %}
                {% endblock %}
            </div>
            {% include "parts/footer.jinja2.html" %}
        </div>
        <a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
    {% include "parts/scripts.jinja2.html" %}
    </body>
{% endblock %}

</html>

pomme/templates/crawl.html
{% extends "base.jinja2.html" %}
{% set active_page = "crawl" %}
{% block content %}
    Hello !
{% endblock %}

pomme/templates/home.html
{% extends "base.jinja2.html" %}
{% set active_page = "home" %}
{% block content %}
    <div class="container-fluid">
        <h3 class="text-dark mb-4">Welcome to Pomme, a Po entries memory</h3>
        <h4 class="text-dark mb-4">Pomme will allow you to quickly search words for their translations along with the context</h4>
    </div>
{% endblock %}

pomme/templates/metrics.html
{% extends "base.jinja2.html" %}
{% set active_page = "metrics" %}
{% block content %}
    Hello !
{% endblock %}

pomme/templates/parts/flashes.jinja2.html
{% block flashes %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <!-- <strong>Title</strong> --> {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
{% endblock %}

pomme/templates/parts/footer.jinja2.html
{% block footer %}
    <footer class="bg-white sticky-footer">
        <div class="container my-auto">
            <div class="text-center my-auto copyright"><span>Copyright © Julien Palard &amp; Jules Lasne 2020</span></div>
        </div>
    </footer>
{% endblock %}

pomme/templates/parts/header.jinja2.html
{% block head %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>Pomme</title>
        <link rel="stylesheet" href="../static/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    </head>
{% endblock %}

pomme/templates/parts/scripts.jinja2.html
{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="../static/js/theme.js"></script>
{% endblock %}

pomme/templates/parts/searchbar.jinja2.html
{% block searchbar %}
    <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
        <div class="container-fluid"><button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
{#            <form class="form-inline d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">#}
{#                <div class="input-group"><input class="bg-light form-control border-0 small" type="text" placeholder="Search for ...">#}
{#                    <div class="input-group-append"><button class="btn btn-primary py-0" type="button"><i class="fas fa-search"></i></button></div>#}
{#                </div>#}
{#            </form>#}
        </div>
    </nav>
{% endblock %}

pomme/templates/parts/sidebar.jinja2.html
{% block sidebar %}
    <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
        <div class="container-fluid d-flex flex-column p-0"><a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="{{ url_for('home.home_view') }}"><img class="img-fluid" src="../static/img/logo.png"></a>
            <hr class="sidebar-divider my-0">
            <strong class="text-light">Po Memory</strong>
            <ul class="nav navbar-nav text-light" id="accordionSidebar">
                {% set navigation_bar = [
                    (url_for("home.home_view"), 'home', 'Home', "fas fa-home"),
                    (url_for("home.metrics_view"), 'metrics', 'Metrics', "fas fa-tachometer-alt"),
                    (url_for("home.search_view"), 'search', 'Search', "fas fa-search"),
                    (url_for("home.crawl_view"), 'crawl', 'Crawl', "fab fa-github"),
                ]
                        -%}

                {% set active_page = active_page|default('index') -%}
                {% for href, id, caption, icon in navigation_bar %}
                    <li class="nav-item">
                        <a {% if id == active_page %} class="nav-link active" {% else %} class="nav-link" {% endif %} href="{{ href|e }}">
                            <i class="{{ icon }}"></i>
                            <span>{{ caption }}</span>
                        </a>
                    </li>
                {% endfor %}
                <li class="nav-item"></li>
                <li class="nav-item"></li>
            </ul>
        </div>
    </nav>
{% endblock %}

pomme/templates/search.html
{% extends "base.jinja2.html" %}
{% set active_page = "search" %}
{% block content %}
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.search_word.label }}<br>
            {{ form.search_word(size=32) }}<br>
            {{ form.id_lang.label }}<br>
            {{ form.id_lang }}<br>
            {{ form.str_lang.label }}<br>
            {{ form.str_lang }}<br>
            {% for error in form.search_word.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
    {% if results %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">rowid</th>
                <th scope="col">msgid</th>
                <th scope="col">msgstr</th>
            </tr>
            </thead>
            <tbody>
            {% for entry in results %}
                <tr>
                    <th scope="row">{{ entry.rowid }}</th>
                    <td>
                        {% for word in entry.msgid.split(" ") %}
                            {% if word|lower == search_word|lower %}
                                <span style="color: red">{{ word }}</span>
                            {% else %}
                                {{ word }}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% for word in entry.msgstr.split(" ") %}
                            {% if word|lower == search_word|lower %}
                                <span style="color: green">{{ word }}</span>
                            {% else %}
                                {{ word }}
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}